/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Gas_Pred */

#ifndef _Included_Gas_Pred
#define _Included_Gas_Pred
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Gas_Pred
 * Method:    GasPredition
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Gas_1Pred_GasPredition
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
